# Generated by Django 3.0 on 2024-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0009_addconsignment_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='accountHolder',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vehicledocument',
            field=models.FileField(blank=True, null=True, upload_to='vehicledocuments/'),
        ),
    ]
