# Generated by Django 3.0 on 2024-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0010_auto_20241223_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='actualweight',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='dlno',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='methodpkg',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
