# Generated by Django 3.0 on 2024-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0011_auto_20241224_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdmprem',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gdmtemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lhstemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='turprem',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='turtemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='actualweight',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
