# Generated by Django 3.0 on 2024-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0013_auto_20241224_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
