# Generated by Django 3.0 on 2024-12-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0014_branch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='receiver_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_foc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_pickup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_tbb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_foc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_pickup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_tbb',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
