# Generated by Django 3.0 on 2025-01-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0016_auto_20241226_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='pay_method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='collectionLocation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='collectionVehicleNo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='pay_method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='receiver_GSTApplicable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='sender_GSTApplicable',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
