# Generated by Django 3.0 on 2025-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0017_auto_20250115_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeF_from', models.CharField(max_length=500, null=True)),
                ('route_to', models.CharField(max_length=500, null=True)),
                ('rate', models.FloatField(null=True)),
            ],
        ),
    ]
