# Generated by Django 3.0 on 2025-01-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0018_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='routeF_from',
            new_name='route_from',
        ),
    ]
