# Generated by Django 3.0 on 2025-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0019_auto_20250115_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cod',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='doorCollection',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='doorDelivery',
            field=models.FloatField(null=True),
        ),
    ]
