# Generated by Django 3.0 on 2025-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0021_auto_20250115_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='weight',
            new_name='paidweight',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='delivery',
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='pay_tbb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='pay_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
