# Generated by Django 3.0 on 2025-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0022_auto_20250115_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='door_charge',
            new_name='cod',
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='collection_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='delivery_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='fov',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='gstcharge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='pkgcharge',
            field=models.FloatField(null=True),
        ),
    ]
