# Generated by Django 3.0 on 2025-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0023_auto_20250115_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='deduction',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
