# Generated by Django 3.0 on 2025-01-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0024_addconsignment_deduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='balance',
            new_name='otherCharge',
        ),
    ]
