# Generated by Django 3.0 on 2025-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0025_auto_20250116_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkgRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg', models.CharField(max_length=500, null=True)),
                ('rate', models.FloatField(null=True)),
            ],
        ),
    ]
