# Generated by Django 3.0 on 2025-01-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0026_pkgrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='prod_invoice',
            new_name='invoiceNo',
        ),
        migrations.RenameField(
            model_name='addconsignment',
            old_name='eway_bill',
            new_name='invoiceType',
        ),
        migrations.RenameField(
            model_name='addconsignment',
            old_name='invoice',
            new_name='invoiceeway',
        ),
        migrations.RenameField(
            model_name='addconsignment',
            old_name='prod_price',
            new_name='invoicevalue',
        ),
    ]
