# Generated by Django 3.0 on 2025-01-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0027_auto_20250116_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='prod_invoice',
            new_name='invoiceNo',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='eway_bill',
            new_name='invoiceType',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='invoice',
            new_name='invoiceeway',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='prod_price',
            new_name='invoicevalue',
        ),
    ]
