# Generated by Django 3.0 on 2025-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0028_auto_20250116_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='vehicleNo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='vehicleNo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
