# Generated by Django 3.0 on 2025-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0029_auto_20250116_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='actualweightvalue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='codapplicable',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='gstapplicable',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='paidweightvalue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='prodDesc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='totaNoPkgs',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='totaactualweight',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='totapaidweight',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='actualweightvalue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='cod',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='codapplicable',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='fov',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='gstapplicable',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='gstcharge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='paidweight',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='paidweightvalue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='pkgcharge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='prodDesc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='totaNoPkgs',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='totaactualweight',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='totapaidweight',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='paidweight',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
