# Generated by Django 3.0 on 2025-01-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0030_auto_20250116_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='totaNoPkgs',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='totaactualweight',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='totapaidweight',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='totaNoPkgs',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='totaactualweight',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='totapaidweight',
        ),
    ]
