# Generated by Django 3.0 on 2025-01-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0031_auto_20250117_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='addconsignment',
            name='vehicleNo',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='location',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='vehicleNo',
        ),
    ]
