# Generated by Django 3.0 on 2025-01-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0032_auto_20250117_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='methodpkg',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='methodpkg',
        ),
    ]
