# Generated by Django 3.0 on 2025-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0033_auto_20250117_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='invoice',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='invoice',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
