# Generated by Django 3.0 on 2025-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0036_auto_20250117_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='deduction',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
