# Generated by Django 3.0 on 2025-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0037_addconsignmenttemp_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='collection_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='delivery_charge',
            field=models.FloatField(null=True),
        ),
    ]
