# Generated by Django 3.0 on 2025-01-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0040_addconsignmenttemp_pay_tbb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('labour', models.CharField(blank=True, max_length=100, null=True)),
                ('lcm_no', models.CharField(max_length=50, unique=True)),
                ('track_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gc_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
