# Generated by Django 3.0 on 2025-01-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0041_lcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcm',
            name='addconsignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gc_details', to='consign_app.AddConsignment'),
        ),
    ]
