# Generated by Django 3.0 on 2025-01-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0042_lcm_addconsignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcm',
            name='lcm_no',
            field=models.CharField(max_length=50),
        ),
    ]
