# Generated by Django 3.0 on 2025-01-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0044_auto_20250118_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCMTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('track_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gc_date', models.DateField(blank=True, null=True)),
                ('consignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consign_app.AddConsignment')),
            ],
        ),
    ]
