# Generated by Django 3.0 on 2025-01-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0045_lcmtemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lcmtemp',
            old_name='location',
            new_name='collectionLocation',
        ),
        migrations.RenameField(
            model_name='lcmtemp',
            old_name='vehicle_no',
            new_name='collectionVehicleNo',
        ),
        migrations.RenameField(
            model_name='lcmtemp',
            old_name='gc_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='actualweight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='desc_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='paidweight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='pieces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='prodDesc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
