# Generated by Django 3.0 on 2025-01-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0046_auto_20250118_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('pickup', models.CharField(max_length=50, null=True)),
                ('tbb', models.CharField(max_length=50, null=True)),
                ('foc', models.CharField(max_length=50, null=True)),
                ('GST', models.CharField(max_length=50, null=True)),
                ('clientType', models.CharField(max_length=50, null=True)),
                ('thirdParty', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delcharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delPlace', models.CharField(max_length=500, null=True)),
                ('rate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TBBRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbbName', models.CharField(max_length=500, null=True)),
                ('tbbId', models.IntegerField(max_length=500, null=True)),
                ('route_from', models.CharField(max_length=500, null=True)),
                ('route_to', models.CharField(max_length=500, null=True)),
                ('rate', models.FloatField(null=True)),
                ('doorCollection', models.FloatField(null=True)),
                ('doorDelivery', models.FloatField(null=True)),
                ('cod', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PkgRate',
            new_name='Pickcharge',
        ),
        migrations.RenameField(
            model_name='pickcharge',
            old_name='pkg',
            new_name='pickPlace',
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchargeName', models.CharField(max_length=50, null=True)),
                ('inchargePhone', models.IntegerField(max_length=50, null=True)),
                ('inchargeRole', models.CharField(max_length=50, null=True)),
                ('inchargeEmail', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consign_app.Client')),
            ],
        ),
    ]
