# Generated by Django 3.0 on 2025-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0048_auto_20250121_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbrate',
            name='tbbId',
            field=models.IntegerField(null=True),
        ),
    ]
