# Generated by Django 3.0 on 2025-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0050_cordelcharge_corpickcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordelcharge',
            name='clientId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cordelcharge',
            name='clientName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='corpickcharge',
            name='clientId',
            field=models.IntegerField(null=True),
        ),
    ]
