# Generated by Django 3.0 on 2025-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0051_auto_20250125_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='gcType',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='thirdPartyId',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='thirdPartyName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='gcType',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='thirdPartyId',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='thirdPartyName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
