# Generated by Django 3.0 on 2025-01-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0052_auto_20250126_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ewaybill_no_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='consign_app.AddConsignment')),
            ],
        ),
        migrations.CreateModel(
            name='AddDc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_no', models.CharField(max_length=255)),
                ('dc_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ewaybill_no_dc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_details', to='consign_app.AddConsignment')),
            ],
        ),
    ]
