# Generated by Django 3.0 on 2025-01-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0053_adddc_addinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddc',
            name='track_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addinvoice',
            name='track_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
