# Generated by Django 3.0 on 2025-01-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0054_auto_20250128_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinvoice',
            name='consignment',
        ),
        migrations.DeleteModel(
            name='AddDc',
        ),
        migrations.DeleteModel(
            name='AddInvoice',
        ),
    ]
