# Generated by Django 3.0 on 2025-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0055_auto_20250128_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lcmtemp',
            old_name='collectionVehicleNo',
            new_name='lcm_no',
        ),
        migrations.RenameField(
            model_name='lcmtemp',
            old_name='collectionLocation',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='lcmtemp',
            name='actualweight',
        ),
        migrations.RemoveField(
            model_name='lcmtemp',
            name='desc_product',
        ),
        migrations.RemoveField(
            model_name='lcmtemp',
            name='paidweight',
        ),
        migrations.RemoveField(
            model_name='lcmtemp',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='lcmtemp',
            name='prodDesc',
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='gc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='labour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='vehicle_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lcm',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lcm',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lcm',
            name='vehicle_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lcmtemp',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
