# Generated by Django 3.0 on 2025-01-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0057_auto_20250129_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='track_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='track_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
