# Generated by Django 3.0 on 2025-01-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0058_auto_20250129_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcmtemp',
            name='collection_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lcmtemp',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
