# Generated by Django 3.0 on 2025-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0059_auto_20250129_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='branchcode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
